# Generated by Django 4.2.2 on 2025-07-26 17:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "time_lead",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Время, когда необходимо выполнять привычку",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        max_length=200,
                        verbose_name="Действие, которое представляет собой привычка",
                    ),
                ),
                (
                    "time_complete",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=120,
                        null=True,
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=1,
                        null=True,
                        verbose_name="Периодичность выполнения привычки",
                    ),
                ),
                (
                    "pleasant_habit_sign",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Признак, указывающий на то, что привычка является приятной, а не полезной",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Награда пользователю после выполнения полезной привычки",
                    ),
                ),
                (
                    "in_publicity",
                    models.BooleanField(
                        blank=True,
                        help_text="Укажите признак публичности",
                        null=True,
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите связанную приятную привычку, в качестве награды. Важно указывать для полезных привычек, но не для приятных",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habit.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
