# Generated by Django 4.2.2 on 2025-07-28 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time_lead",
            field=models.TimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Время, когда необходимо выполнять привычку",
            ),
        ),
    ]
